// Code generated by "stringer -type=ParameterType"; DO NOT EDIT.

package scraper

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParameterTypeValue-1]
	_ = x[ParameterTypeInput-2]
	_ = x[ParameterTypeMix-3]
	_ = x[ParameterTypeDuration-4]
	_ = x[ParameterTypeChannel-5]
	_ = x[ParameterTypeUnknown-6]
}

const _ParameterType_name = "ParameterTypeValueParameterTypeInputParameterTypeMixParameterTypeDurationParameterTypeChannelParameterTypeUnknown"

var _ParameterType_index = [...]uint8{0, 18, 36, 52, 73, 93, 113}

func (i ParameterType) String() string {
	i -= 1
	if i < 0 || i >= ParameterType(len(_ParameterType_index)-1) {
		return "ParameterType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ParameterType_name[_ParameterType_index[i]:_ParameterType_index[i+1]]
}
