// Code generated by "stringer -type=ParameterType"; DO NOT EDIT.

package scraper

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ParameterTypeNone-0]
	_ = x[ParameterTypeValue-1]
	_ = x[ParameterTypeInput-2]
	_ = x[ParameterTypeDuration-3]
	_ = x[ParameterTypeChannel-4]
	_ = x[ParameterTypeUnknown-5]
}

const _ParameterType_name = "ParameterTypeNoneParameterTypeValueParameterTypeInputParameterTypeDurationParameterTypeChannelParameterTypeUnknown"

var _ParameterType_index = [...]uint8{0, 17, 35, 53, 74, 94, 114}

func (i ParameterType) String() string {
	if i < 0 || i >= ParameterType(len(_ParameterType_index)-1) {
		return "ParameterType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParameterType_name[_ParameterType_index[i]:_ParameterType_index[i+1]]
}
