# .goreleaser.yml
version: 2

project_name: vmix-utility

before:
  hooks:
    # フロントエンドのビルド
    - cd web && yarn install --frozen-lockfile
    - cd web && yarn build

builds:
  - main: ./main.go
    id: "vmix-utility"
    binary: vmix-utility
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    # Windows用はzipファイル
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: FlowingSPDG
    name: vmix-utility
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"

# Git submodule vMixMultiviewを含める必要がある場合
git:
  ignore_tags:
    - "nightly"