language: go
dist: xenial
sudo: false
cache: yarn
git:
  depth: 1
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - make deps
matrix:
  include:
    - language: go,node_js
      go: 1.13.5
      node_js:
        - '14'
      
      script:
        - make